# @package __global__

classifier_free_guidance:
  training_dropout: 0.1
  inference_coef: 3.0

attribute_dropout: {}

fuser:
  cross_attention_pos_emb: false
  cross_attention_pos_emb_scale: 1
  sum: []
  prepend: []
  cross: [description]
  input_interpolate: []

conditioners:
  video_path:  ## This is the conditioning attribute that will be the key in the dictionary in get_conditioning_provider()
    model: imagebind
    t5:
      name: imagebind
      finetune: false
      word_dropout: 0.
      normalize_text: false